IAM Policies Blogpost
ocelotconsulting/ocelotconsulting.github.io pull request #194
Opened 2023-08-31 14:41 UTC by martyjhenderson

This PR:
* Copies blog post from Marty's blog
* Adds the cabinet image used as a header

2023-08-31 15:05 UTC, martyjhenderson commented
I plan on changing the date into the future, but left it as today in order to let people preview it.

2023-09-11 14:08 UTC, PMByrne requested changes

2023-09-11 14:08 UTC, PMByrne commented on public/assets/insights/cabinets-unsplash.jpg
Image needs to be scaled down a bit resolution wise.

2023-09-11 20:36 UTC, martyjhenderson commented on public/assets/insights/cabinets-unsplash.jpg
It has been converted to webp, thereby is much smaller

2023-09-12 00:51 UTC, PMByrne approved these changes

2023-09-12 00:51 UTC, merged